ALTER RESOURCE GOVERNOR WITH (CLASSIFIER_FUNCTION = NULL);
GO
ALTER RESOURCE GOVERNOR RECONFIGURE; 
GO

CREATE FUNCTION UserClassifier() RETURNS SYSNAME WITH SCHEMABINDING

BEGIN

	DECLARE @val varchar(32)
	SET @val = 'default';

	IF 'service_user' <> SUSER_SNAME()
	SET @val = 'WGLow';

	RETURN @val;

END 